### ISSUE TITLE
On iOS App is not show up in the share list

### ISSUE THREAD

**Issue by viktorRot** [meedan/react-native-share-menu#172]
Hi,

my app does not appear in the share list when I try to share a website content / url from browser with my App. Android is working fine.

Last week it worked also for iOS but then I required to upgrade to Xcode **13.2.1** and iOS **15.2**. Since then it is no longer working. I followed the instructions for the setup several times and I'm in the meantime pretty sure that I did the setup correctly like described in: https://github.com/meedan/react-native-share-menu/blob/master/IOS_INSTRUCTIONS.md

It's not working on a simulator with iOS 15.2 and also not on my iphone 8 which I use as test device which have iOS 14.5.1.

Does someone has an idea?

Thanks a lot in advance!

**Comment by viktorRot** [comment]
After setup everything one more time, it worked. Cannot reproduce this issue anymore.

**Comment by ramirobg94** [comment]
Other here

**Comment by AlejoBidari** [comment]
Is there any update on this? I've been trying to fix this issue for a long time now with no results. Even completing the whole process of installation from the beginning. I also can't find any alternative to this library.

**Comment by shaynethiessen** [comment]
> Is there any update on this? I've been trying to fix this issue for a long time now with no results. Even completing the whole process of installation from the beginning. I also can't find any alternative to this library.

I haven't been able to find any alternative either and this library doesn't seem to be maintained anymore 😞

**Comment by AlejoBidari** [comment]
@shaynethiessen I gave up and made a release to Test Flight (Apple's app testing environment) and the option to share appeared again! I still can't see it when running either debug or release versions directly from xCode but at least it works in "production". I'll come back to you when I do a release to the App Store to see if it stays that way (hopefully).

All the development has to be done from an Android environment, unfortunately. I was lucky to already have it working before the xCode or iOS version that broke it and I had everything set up.

**Comment by shaynethiessen** [comment]
@AlejoBidari Thanks for the information. I appreciate it.

**Comment by AlejoBidari** [comment]
I can confirm that the app appears in the share list when released to the App Store. 🚀

If someone finds how to make it work from xCode for development please let me know, I will very much appreciate it 🙏
