### ISSUE TITLE
Creating Custom Share View using Javascript

### ISSUE THREAD

**Issue by Bayramito** [meedan/react-native-share-menu#175]
Hi,

I just wonder isn't there any better and easier way to create custom share view using jsx ?

I just want to popup my own thing when i hit my app's icon from the share menu but it only shows a texf input and post button

**Comment by xmflsct** [comment]
Follow this then you have it, https://github.com/meedan/react-native-share-menu/blob/master/SHARE_EXTENSION_VIEW.md
