### ISSUE TITLE
[Question] [iOS] Image shared does not have the right permission in the app?

### ISSUE THREAD

**Issue by xmflsct** [meedan/react-native-share-menu#181]
After trying for several hours, I finally get this module working. I have a React Native app that is powered by Expo bare workflow. I cannot figure out how to install Expo pods into the share extension, thus I will need my app to handle all the logic instead of the share extension.

So far when sharing both text and image, the share extension can evoke my app without problem. I have patched manually with this PR https://github.com/meedan/react-native-share-menu/pull/158 to support multiple images. So far when the app is launched, the `data` field is empty, but `extraData` field can be used. I then pass image data through `extraData` field, but when in the app, it seems the path of the image cannot be loaded. How can I debug permission issue? Thanks!

**Comment by mircogrosch** [comment]
@xmflsct Can you run in real device?. When I run in Release mode, I can't show share view.  It only shows me a blank screen

**Comment by xmflsct** [comment]
Turns out that it is indeed a permission issue. I need to copy the file to a cache place that is shared among app within the App Groups, then React Native can assess it properly. See https://github.com/itinance/react-native-fs/issues/640.

**Comment by xmflsct** [comment]
@mircogrosch yes I just test it through TestFlight and it works on real device. Though it currently only gets data when the app is fully closed. Need to figure out why the app does not receive data when it is running in the background.
