### ISSUE TITLE
[iOS] Build failed with error: 'RNShareMenu-Swift.h' file not found

### ISSUE THREAD

**Issue by gartnerleandro** [meedan/react-native-share-menu#217]
Hi! I get an error when I build my iOS app using Xcode 14.0.1

![ISSUE](https://user-images.githubusercontent.com/14914751/197386613-1f7d493c-bec6-41fa-b806-12bfa3ad565e.png)

```
/node_modules/react-native-share-menu/ios/ShareMenuManager.m:9:9: fatal error: 'RNShareMenu-Swift.h' file not found
#import "RNShareMenu-Swift.h"
        ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

My Podfile:

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

$RNFirebaseAsStaticFramework = true

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false
use_frameworks! :linkage => :static

target 'myapp' do
  config = use_native_modules!
  use_modular_headers!
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  target 'myappTests' do
    inherit! :complete
    # Pods for testing
  end

  def find_and_replace(dir, findstr, replacestr)
    Dir[dir].each do |name|
        text = File.read(name)
        replace = text.gsub(findstr,replacestr)
        replaced = text.index(replacestr)
        if replaced == nil && text != replace
            puts "Fix: " + name
            File.open(name, "w") { |file| file.puts replace }
            STDOUT.flush
        end
    end
    Dir[dir + '*/'].each(&method(:find_and_replace))
  end
  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
  end
end

target 'ShareExtension' do
  use_react_native!

  pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
  # Manually link packages here to keep your extension bundle size minimal
end
```

Log:

```
** BUILD FAILED **


The following build commands failed:
	Run custom shell script 'Run Script'
	CompileC /Xcode/DerivedData/wiset-gryawechizmnljdbebcbfbdthczk/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNShareMenu.build/Objects-normal/x86_64/ShareMenuManager.o /myapp/node_modules/react-native-share-menu/ios/ShareMenuManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNShareMenu' from project 'Pods')
(2 failures)
```

react-native: 0.70.0
react-native-share-menu: 6.0.0

I'm having this error since I update my react-native version.

**Comment by brusenskiy** [comment]
Same issue :-(

**Comment by jorgemorazan** [comment]
I had this issue yesterday and resolved just now. Make sure to have `iOS Deployment Target` value the same for the extension and the project. 

But what resolved me the issue is that I was developing for iPhone only and not iPad. In the `ExtensionShare` target, by default, it had the iPad in the `Targeted Device Families`. I removed the iPad and it started working.

**Comment by monokaijs** [comment]
I faced the same issue here. And the problem is about:
```
use_frameworks! :linkage => :static
```
Please remove your configuration and use this if you're using firebase:
```
target 'YourApp' do
  # ...
  use_react_native!(
    :hermes_enabled => true,
    # ...
  )
  # ...
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  $RNFirebaseAsStaticFramework = true
  # ...
end

# ...

target 'YourShareExtension' do
  use_react_native!(
    :hermes_enabled => true,
  )

  pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
end

```

Good luck!

**Comment by bizarrecoding** [comment]
I managed to fix this issue by changing the import style
In my case I happen to call use_frameworks!  in my pod file. It created a file RNShareMenu.framework file where the missing file is found inside.

```
// node_modules/react-native-share-menu/ios/ShareMenuManager.m
#import "ShareMenuManager.h"
-#import "RNShareMenu-Swift.h"
         ^~~~~~~~~~~~~~~~~~~~~
+#import <RNShareMenu/RNShareMenu-Swift.h>
 
#import <React/RCTLinkingManager.h>
```

**Comment by brusenskiy** [comment]
> I managed to fix this issue by changing the import style In my case I happen to call use_frameworks! in my pod file. It created a file RNShareMenu.framework file where the missing file is found inside.
> 
> ```
> // node_modules/react-native-share-menu/ios/ShareMenuManager.m
> #import "ShareMenuManager.h"
> -#import "RNShareMenu-Swift.h"
>          ^~~~~~~~~~~~~~~~~~~~~
> +#import <RNShareMenu/RNShareMenu-Swift.h>
>  
> #import <React/RCTLinkingManager.h>
> ```

It solved problem locally! Will use patch-package to update file.

Thanx.

**Comment by monokaijs** [comment]
> > I managed to fix this issue by changing the import style In my case I happen to call use_frameworks! in my pod file. It created a file RNShareMenu.framework file where the missing file is found inside.
> > ```
> > // node_modules/react-native-share-menu/ios/ShareMenuManager.m
> > #import "ShareMenuManager.h"
> > -#import "RNShareMenu-Swift.h"
> >          ^~~~~~~~~~~~~~~~~~~~~
> > +#import <RNShareMenu/RNShareMenu-Swift.h>
> >  
> > #import <React/RCTLinkingManager.h>
> > ```
> 
> It solved problem locally! Will use patch-package to update file.
> 
> Thanx.

You can use [patch-package](https://www.npmjs.com/package/patch-package) to achieve this.

**Comment by gartnerleandro** [comment]
> I faced the same issue here. And the problem is about:
> 
> ```
> use_frameworks! :linkage => :static
> ```
> 
> Please remove your configuration and use this if you're using firebase:
> 
> ```
> target 'YourApp' do
>   # ...
>   use_react_native!(
>     :hermes_enabled => true,
>     # ...
>   )
>   # ...
>   pod 'Firebase', :modular_headers => true
>   pod 'FirebaseCore', :modular_headers => true
>   pod 'GoogleUtilities', :modular_headers => true
>   $RNFirebaseAsStaticFramework = true
>   # ...
> end
> 
> # ...
> 
> target 'YourShareExtension' do
>   use_react_native!(
>     :hermes_enabled => true,
>   )
> 
>   pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
> end
> ```
> 
> Good luck!

Thanks you! This was the solution for me

**Comment by nextdaysoft** [comment]
> #import <RNShareMenu/RNShareMenu-Swift.h>

Thanks you!

**Comment by Gamote** [comment]
I think it's better to create a patch so you don't have to adapt you firebase configuration. Simply create a patch that is checking for both locations.

File: `patches/react-native-share-menu+5.0.5.patch`:
```patch
diff --git a/node_modules/react-native-share-menu/ios/ShareMenuManager.m b/node_modules/react-native-share-menu/ios/ShareMenuManager.m
index 308ec99..3c92827 100644
--- a/node_modules/react-native-share-menu/ios/ShareMenuManager.m
+++ b/node_modules/react-native-share-menu/ios/ShareMenuManager.m
@@ -6,7 +6,14 @@
 //
 
 #import "ShareMenuManager.h"
+
+// `use_frameworks!` moves this file to a different location
+// See: https://github.com/meedan/react-native-share-menu/issues/217#issuecomment-1301608521
+#if __has_include(<RNShareMenu/RNShareMenu-Swift.h>)
+#import <RNShareMenu/RNShareMenu-Swift.h>
+#else
 #import "RNShareMenu-Swift.h"
+#endif
 
 #import <React/RCTLinkingManager.h>
 

```

Add this to your `package.json`:
```patch
 "scripts": {
+  "postinstall": "patch-package"
 }
```

And install `patch-package`: `yarn add patch-package postinstall-postinstall`.
