### ISSUE TITLE
IOS: My app will not show on the share menu

### ISSUE THREAD

**Issue by Vatousiadis** [meedan/react-native-share-menu#232]
Hello and thanks for the great package.
Implementation with android works fine and everything is nice and smooth
My problem lies with iOS implementation, where after doing the steps 2 times, i cannot seem to get the my app to show in the share menu. I use NSExtensionActivationRule for image,url,text but non show in the share menu of other apps.

I am using an emulator (on iOS 15.2) and xCode v13, as well ass RN v0.69.2
Any kind of help would be really appreciated!

**Comment by Vatousiadis** [comment]
self-closing since i found the miss-configuration i have done, make sure tou tripple check those stuff ppl, thanks again for the great package!

**Comment by ghost** [comment]
@Vatousiadis can you mention what you miss configured? because I'm facing the same issue.

**Comment by Vatousiadis** [comment]
> @Vatousiadis can you mention what you miss configured? because I'm facing the same issue.

After such a long time i can't really remember. But what i usually do since it can be a configuration probem

- Scrap All changes
- Re-read carefully the docs and installation proccess
- Re-apply the configurations

Pretty basic I know, but i hope this helps you out a bit
