### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by lindboe** [meedan/react-native-share-menu#254]
My team is evaluating using this library, and we notice that there haven't been updates in about a year, while there are waiting PRs and issues with newer versions of React Native (like [this example](https://github.com/meedan/react-native-share-menu/issues/209)). We'd be happy to work on contributing, but if pull requests aren't currently being addressed that would not be possible.

What is this project's maintenance status? Are you looking for maintainers? Is it best to fork?

Tagging @caiosba as you have the most recent commits, and @Gustash as you're mentioned as a maintainer.

Thanks for your time.

**Comment by caiosba** [comment]
Yes, I haven't been able to review the PRs for a long time. Would be great if someone is interested in maintaining it. We should probably fork since it's under an organization account that is not supporting the project anymore.

**Comment by acopetkovic** [comment]
Hi @lindboe, did you manage to successfully include this library in your project? I'm currently looking for a solution since share extension / share intent is big part of my side project. Please let me know if this or maybe other library can be used for both Android and iOS since I didn't have much luck finding good solution. Thanks!

**Comment by saif-o99** [comment]
@caiosba @lindboe guys did anyone forked this project to replace this one? I'd like to contribute

**Comment by lindboe** [comment]
Hi, yes, @caiosba we'd like to help with maintenance. We specifically want to use this library for [Expensify](https://github.com/Expensify/App/), so it would be good to get a maintainer from Infinite Red like myself for the project, but also someone from the Expensify team (I can get a name soon). Does that work for you @caiosba?

**Comment by caiosba** [comment]
@lindboe yes that would be great! maybe we can even discuss it? I would like to see how I can help with limited availability too and hand off this project

**Comment by lindboe** [comment]
@caiosba Sure thing! What kind of discussion are you thinking of? Here is good, or if it's to chat more frequently, we have the[ Infinite Red community Slack](https://community.infinite.red), or we're happy to set up a Zoom call. @jamonholmgren (Infinite Red's CTO) would be good to involve as well.

**Comment by caiosba** [comment]
Yeah we can keep talking here. I'm thinking that we could fork/move this project to another organization (maybe its own?) and have other people as maintainers to the project. We can start by just adding a couple of new maintainers, and also for the NPM package. Happy to jump sometime on a quick Zoom call for introductions and to get things on faster if needed.

**Comment by jamonholmgren** [comment]
Just my 2 cents ... if Expensify will be funding the majority of ongoing development going forward, I'd probably recommend that we move it to their Github org. It tends to accomplish two things -- make it feel worthwhile for them to invest in it, and also give them a sense of ownership that helps for long-term sustainability. (I get there are other factors involved though!)

**Comment by lindboe** [comment]
Hi @caiosba, following up. Expensify would like to bring this project into their organization. @andrewgable from Expensify would be the maintainer to add from their side, and I can be a maintainer for the Infinite Red side to fix some of the issues we ran into. Does that work for you?

**Comment by caiosba** [comment]
Yes, that works for me, thanks @lindboe . I just ask that we please keep the mention to Meedan as initial sponsor and supporter of this work (e.g., in the README). How does it sound?

**Comment by lindboe** [comment]
That sounds reasonable to me, but I'll leave it up to @andrewgable to confirm. (I think it would be a good idea to add a comment in the README to ensure that isn't removed.)

**Comment by AndrewGable** [comment]
Yes, totally fine to keep the original maintainers and sponsors included 👍

**Comment by jamonholmgren** [comment]
Totally reasonable, and thank you @caiosba and Meedan for your hard work on this library over the years!

**Comment by acopetkovic** [comment]
Where can I follow the progress of forked repo? I would love to use it.

**Comment by lindboe** [comment]
We should be able to [transfer the repo to Expensify](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) instead of forking it. That would make for the smooth transition, GitHub would transfer over everything relevant and redirect people.

**Comment by MichaelReaNZ** [comment]
This a great idea, newer versions of React Native and Expo support would be amazing.

**Comment by ice-cap0** [comment]
Awesome stuff

Hopefully this collab will also move the # 3 feature request on Expo forward :)

https://expo.canny.io/feature-requests/p/share-extension-ios-share-intent-android

**Comment by lindboe** [comment]
@caiosba is there anything else you need in order to proceed?

**Comment by caiosba** [comment]
@lindboe , I think I need to have access to the destination organization in order to be able to move it over.

**Comment by lindboe** [comment]
@AndrewGable How would you like to handle the transfer steps? I believe, from reading [the transfer docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository), the repo owner needs to be the one to do the transfer, and that person also needs to be able to create repositories on the target organization. So the two possibilities are:

1. Give @caiosba access to create repos on the Expensify org
2. @caiosba would transfer ownership to @AndrewGable's personal account, and then Andrew would transfer ownership to the Expensify org from there

**Comment by caiosba** [comment]
Either works for me, just let me know :)

**Comment by caiosba** [comment]
Then we need to see what/if we need to do anything on the NPM registry side.

**Comment by AndrewGable** [comment]
@caiosba - I think it would be easiest to transfer to my personal org, I will make sure it moves over to Expensify Org. Also my NPM user name is the same ([AndrewGable](https://www.npmjs.com/~andrewgable)), or if you can transfer it to the [Expensify](https://www.npmjs.com/~expensify) Org on NPM I have access there too.

**Comment by caiosba** [comment]
I had to transfer the repository first to my personal account, but it's now being transferred to @AndrewGable.

**Comment by AndrewGable** [comment]
FYI - Repo has been transferred to Expensify Org.

**Comment by bytehala** [comment]
Happy to see that this project will live on. I'm open to contributing as well, watching for contribution guidelines.

**Comment by jadhaidar** [comment]
Happy to contribute as well.

**Comment by lssilveira11** [comment]
Hi everyone! Any news about future releases or PRs merges? I think there's some important PRs like #260 that would be great to be accepted.

**Comment by skitscha** [comment]
@caiosba Would you be able to review some of the PRs sitting out there?

**Comment by MichaelReaNZ** [comment]
Haven't seen any changes in a long time is this project still alive?

Why is it so hard for a shareTo on an app in 2023... 😭

**Comment by lindboe** [comment]
Hey folks, sorry for the delay, we've been in the middle of planning out this project further.

We've got a plan for the updates we're going to make to specifically support Expensify here: #294.

As I say on the linked issue, if you have concerns that we don't plan to address, and you'd like to submit a PR yourself, please discuss with us on #294, and we'll make a plan together.

**Comment by lindboe** [comment]
Closing this issue out as we have more specific tickets to work on now, and we can follow up on any handoff needed for managing releases on https://github.com/Expensify/react-native-share-menu/issues/289.

**Comment by walshie4** [comment]
Is this still the case?  Appears to have very little movement recently

Also just noticed this https://github.com/Expensify/react-native-share-menu/issues/293#issuecomment-2240379959 which makes me believe it is no longer being maintained.
