### ISSUE TITLE
Android configuration is out-of-date

### ISSUE THREAD

**Issue by lindboe** [meedan/react-native-share-menu#261]
The Android build configuration has not been updated in a while, and it's causing issues. On Expensify, we see `In order to compile Java 9+ source, please set compileSdkVersion to 30 or above.`

Other related issues:
* https://github.com/Expensify/react-native-share-menu/issues/216
* https://github.com/Expensify/react-native-share-menu/issues/241

We should catch up with the React Native template.

**Comment by asafratzon** [comment]
Confirm to experience the same issue - the package is now incompatible with Expo SDK latest version (49) and breaks android build if included in package.json.
@lindboe are there active maintainers? if so do you reckon this will be fixed soon? 🤞 🙏 

P.S. this package is one of the most desired (missing) Expo features so surely many of us are Expo users...

**Comment by asafratzon** [comment]
As a workaround I was able to fix this issue by patching the `node_modules/react-native-share-menu/android/build.gradle` file from:
```
android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    lintOptions {
       warning 'InvalidPackage'
    }
}
```
to:
```
android {
    defaultConfig {
        compileSdkVersion 31
        minSdkVersion 16
        targetSdkVersion 31
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    lintOptions {
       warning 'InvalidPackage'
    }
}
```

I wasn't sure if this is the correct way to fix it, but it does the job for me and everything works as expected with Expo latest SDK v49.0.6.

Until library is fixed you may test this locally by modifying the file, if you want this to be applied automatically you can use [patch-package](https://www.npmjs.com/package/patch-package) or [pnpm patch](https://pnpm.io/cli/patch) if you use pnpm like myself.

**Comment by zhe1ka** [comment]
may we have a patch for that for v6?
