### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by henrikzabel** [meedan/react-native-share-menu#299]
I am using:
react-native-share-menu 6.0.0
react-native 0.73.1
react 18.2.0

When trying to build the app following error occurs:
`
* What went wrong:
Could not determine the dependencies of task ':react-native-share-menu:bundleLibCompileToJarDebug'.
> Could not create task ':react-native-share-menu:compileDebugJavaWithJavac'.
   > In order to compile Java 9+ source, please set compileSdkVersion to 30 or above
`

I just upgraded react native today. Before the react native upgrade I was able to use this library just fine.

**Comment by henrikzabel** [comment]
#261 was able to solve this problem. I have just seen that there will be a major update soon. Therefore I am closing this issue.

**Comment by Arshad-Ali-1a** [comment]
I was still, facing this issue.
But was able to fix it by changing the compileSdkVersion to `compileSdkVersion 30` in `node_modules/react-native-share-menu/android/build.gradle`

**Comment by jaaywags** [comment]
> I was still, facing this issue. But was able to fix it by changing the compileSdkVersion to `compileSdkVersion 30` in `node_modules/react-native-share-menu/android/build.gradle`

Genius. I set mine to 
```
compileSdkVersion 34
buildToolsVersion "34.0.0"
```

**Comment by aouiniamine** [comment]
I had the same issue with another library. For anyone who needs to fix it without editing node_modules

Edit your ROOT/android/build.gradle To:

```
buildscript {
   ext {
        buildToolsVersion = 'x.0.0'
        compileSdkVersion = x
        
    }
   
    subprojects { subproject ->
        afterEvaluate{
            if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
                android {
                    compileSdkVersion rootProject.ext.compileSdkVersion
                    buildToolsVersion rootProject.ext.buildToolsVersion
                }
            }
        }
    }
}

```
